name: Docker Image CI
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic Release
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          bump_each_commit: true
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: Create env file
        run: |
          echo "APP_PORT=8080" >> .env
          echo "STAGE=production" >> .env
          echo "APP_IMAGE=${{ secrets.DOCKERHUB_USER }}/istore-core:${{ steps.version.outputs.version }}" >> .env
          cat .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker compose build

      - name: Push the Docker image
        run: |
          docker compose push
